# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bd290d611633c02423a842d2548727b03502aeaf4be28046ac27fe1dcaba373e30a3356f60f24917ce7db07e67d38af7362f5256ae63e8fd9818819551aa327

test:
  secret_key_base: 6979f90d04162be39ee3ad49992e02c01a3ab7f7dc510ea3a50106303b5ed0c9ef28fd3595e738a5273bddf5441ec131c165e6376cd02d100274565f1fb94c62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
